- lua/notify/init.lua
Really tiny fix.
I found `notify._print_history()` function removes space between icon and message if the notification doesn't have a title.
Remove useless conditional statement `#notif.title[1] > 0`
> fix(history): add space between icon and message

- lua/telescope/_extensions/notify.lua
Fixes: when no notification selected, either due empty notification history or filter removing all valid selection, a nil error occurred.
```
E5108: Error executing lua ...r/start/nvim-notify/lua/telescope/_extensions/notify.lua:67: attempt to index local 'selection' (a nil value)
stack traceback:
...r/start/nvim-notify/lua/telescope/_extensions/notify.lua:67: in function 'run_replace_or_original'
...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:338: in function 'execute_keymap'
[string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
> Telescope notify – Avoid nil error when nothing is selected

- doc/nvim-notify.txt
- lua/notify/config/init.lua
- lua/notify/init.lua
- lua/notify/stages/fade.lua
- lua/notify/stages/fade_in_slide_out.lua
- lua/notify/stages/init.lua
- lua/notify/stages/slide.lua
- lua/notify/stages/static.lua
This allows setting `config.direction` and refactors each stage to be a function which takes the direction as an argument. The direction from the config is then passed to the style that is set.
Not sure what your thoughts are re. this approach @rcarriga, if it seems alright to you then I'll add some docs for it
> feat(config): allow setting a default direction

- lua/notify/render/simple.lua
I would like to propose a simple render style in between "default" and "minimal", namely only showing (centred) title (with no icons and timestamps) and notification message: see rendering examples in the screenshots below
I have tweaked the original `default.lua` to centre the title and remove the spurious spaces, it should work fine with all use cases (but perhaps there are cases I have not considered - I am just slowly familiarising with the code): what do you think?
> added simple render style

- lua/notify/service/buffer/init.lua
- lua/notify/service/init.lua
- lua/notify/windows/init.lua
Some Noice users like to do `%bw` to wipe all buffers (which they shouldn't do, but anyway). This leads to issues in Noice, Nui and Notify.
I've just fixed them all in each project.
Fixes:
> fix: make notify work when wiping all buffers with %bw

- lua/notify/stages/util.lua
Minor documentation corrections:
`M.DIRECTION` values are all strings, Lua LSP detected the type error while the values in function calls were correct. Example:
In
```lua
local next_row = stages_util.available_slot(state.open_windows, next_height, stages_util.DIRECTION.BOTTOM_UP)
````
`stages_util.DIRECTION.BOTTOM_UP` is a string, and is the correct value that should be used here. But since the `available_slot` method was expecting an integer, LSP complained (even though the code still works since lua is dynamically typed).
Same with `window_intervals` method.
> Correct type of direction variable. It M.DIRECTION values are strings.

- README.md
- lua/notify/render/compact.lua
As of now there is a colon before the message even if there's no title before it, so this PR removes the colon only if there's no title in the message config
> bugfix(rendering): hide `:` if the title is missing in the `compact` renderer

- README.md
- doc/nvim-notify.txt
- lua/notify/render/wrapped-compact.lua
This is an alternative to the `compact` renderer, with the following modifications:
- it adds wrapping, a feature requested numerous times (#137 #88 #143 #129)
- it simulates padding (by prepending a space on every line 🙈). (#152)
- handles the title in a more sensitive manner: if there is a manual title, it becomes a header line, if there is no title given, just prepend the icon.
here is an example with `max_width = 40` for the following notification call
```lua
vim.notify("Hello World. Lorem ipsum dolor sit amet qui minim labore adipisicing minim sint cillum sint consectetur cupidatat.", vim.log.levels.INFO, {title = "My Plugin"})
```
> feat: new renderer `wrapped-compact`

- lua/notify/config/init.lua
- lua/notify/init.lua
- lua/notify/service/notification.lua
- lua/telescope/_extensions/notify.lua
Allow the time format for the notification history & the notifications themselves to be customized.
Handy for those who don't do 24h clocks.
I did consolidate 2 formats:
https://github.com/rcarriga/nvim-notify/pull/214/files#diff-cc0264adaefdad4a3e145a4ad44a0c98f186d24da90e022e9215f3ef68fa828bL32
and
https://github.com/rcarriga/nvim-notify/pull/214/files#diff-3eb94df4dcd115e2877155af0a02b9cee18d96cc0b1ff3a908459b63fd6948cdL46
Since `%T` is `%H:%M:%S` I imagined that the fact that they differ wasn't intentional. Let me know if you want me to separate them.
> feat: allow custom time format

- lua/notify/stages/no_animation.lua
This style has no animations (similarly as `static`), but after any notification dissapears, the rest adjust their positions (fall up/down as in `fade_in_slide_out`).
_Not sure about the naming of the style, I am open to other suggestions._
> feat: add `no_animation` style

- lua/notify/config/init.lua
Neovim now sets termguicolors default to true if the terminal supports it. However, the option is not set until VimEnter, and this means that reading the value of termguicolors will always be false if the user has not set it in their config.
After I removed the unnecessary default option after updating neovim, I always get the warning now.
Check the version as well before warning since termguicolors is now set to true by default if the terminal supports it
> fix: only warn for termguicolors if version minor < 10

- lua/notify/config/init.lua
Checking only the minor version is not technically correct for this check. It probably won't be a big deal because 1.0 is quite a bit away, but this does protect against this.
> fix: improve correctness of neovim version checking

- lua/telescope/_extensions/notify.lua
Addresses https://github.com/rcarriga/nvim-notify/issues/234 allowing notification text to wrap in the telescope preview window to accommodate its fixed width.
> fix(telescope): enable wrap on preview

- lua/notify/service/notification.lua
vim.tbl_add_reverse_lookup has been deprecated since NVIM 0.10.
Deprecations warnings will be raised since 0.11-dev.
> fix: do not use the deprecated API vim.tbl_add_reverse_lookup

- lua/notify/config/init.lua
- lua/notify/service/buffer/highlights.lua
- lua/notify/service/init.lua
- lua/notify/windows/init.lua
Instead of letting the `:hl` to redraw all things globally, use the `nvim__redraw` api to limit the redraw on the notification windows only. The api also handles the case of redrawing during blocking events by flushing the screen changes.
---
Mitigate the issues #56, #63 and #273.
After some investigation, it came down to two culprits:
1. The constant `:hl` commands (for fade in/out blending) that caused frequent global redraws.
2. Good amount of notification window resizing/repositioning.
This PR tickles the first one but couldn't fully eliminate the issue. In situations when the redraws are intense, e.g. many/fat notifications fade in/out around the same time, the problem can still occur. However, even in those situations, the flickering issue would disappear as soon as all the fade …
> perf: mitigate the cursor flickering issue

- lua/notify/integrations/fzf.lua
- lua/notify/integrations/init.lua
- Added support for fzf-lua, it behaves similarly to telescope.
- Implemented `require("notify.integrations").pick()` function to automatically open the available picker.
> feat(picker): add support for fzf

- lua/notify/render/default.lua
- Removing spaces around the icon from the title when the icon is empty.
I just want to disable icons, so I'm setting icons to be empty. For now, although we set icons to be empty, spaces for icons are still inserted into the title. Hence, it does not align with the title and the body.
> fix: remove unnecessary spaces when the icon is empty

- lua/notify/service/init.lua
The `message` parameter is also allowed to be a list of strings. Hence, compared to the previous message, it's viewport dimensions can change both horizontally and vertically.
This sets the existing window width & height to fit the new notification buffer.
---
To reproduce the issue, run this snippet on the master.
```lua
local prev = require("notify")("Somewhat long initial test message", "INFO", { title =  "Note" })
require("notify")({ "A multi line", "replacement" }, nil, { replace = prev })
```
Notice the notification body only contains the string "A multi line". The second "replacement" line is not visible.
And here's the expected result with this change:
> fix: Resizes notification window on replace

- lua/notify/instance.lua
First of all, nice plugin. And the replace existing feature makes it even better. I enjoyed integrating it into [rspec-integrated.nvim](https://github.com/melopilosyan/rspec-integrated.nvim/blob/main/lua/rspec/notif.lua).
So. To reproduce the bug, execute this snippet on the master.
```lua
local prev = require("notify")("Won't show up in history", "INFO", {
title =  "Note",
hide_from_history = true,
})
require("notify")("Should show up, but doesn't", nil, {
replace = prev,
hide_from_history = false,
})
```
Then run the `:Notifications` command and notice the empty history. Although the second one is told not to hide.
> fix: Corrects copying options from existing notification for boolean values

- lua/notify/render/compact.lua
- lua/notify/render/default.lua
- lua/notify/render/simple.lua
- lua/notify/render/wrapped-compact.lua
- lua/notify/service/buffer/init.lua
- tests/unit/init_spec.lua
I found that sometimes notifications are not rendered correctly. Here is an example:
```lua
local notify = require("notify")
local title = "\u{1D4AF}\u{212F}\u{1D4C8}\u{1D4C9}" -- "𝒯ℯ𝓈𝓉"
notify("Title not correctly highlighted", nil, { title = title, render = "compact" })
notify("Borderline too short", nil, { title = title, render = "simple" })
```
Such glitches can be caused by several factors: UTF-16 surrogate pairs (accidentally taken into account [here](https://github.com/rcarriga/nvim-notify/blob/80b67b265530632505193553d05127ae7fe09ddd/lua/notify/service/buffer/init.lua#L114) and [here](https://github.com/rcarriga/nvim-notify/blob/80b67b265530632505193553d05127ae7fe09ddd/lua/notify/service/buffer/init.lua#L129)), [combining character …
> fix: improve string width calculation

- lua/notify/render/default.lua
- lua/notify/render/simple.lua
- lua/notify/util/init.lua
- tests/unit/init_spec.lua
Some misbehaving plugin code was sending very large messages to `vim.notify()`, which would trigger an exception when calculating the max line width for rendering:
```
[...]/notify/render/default.lua:6: too many results to unpack
```
To fix this, I updated the implementation to calculate the max line width in-place. This ultimately ends up being much more efficient because it is not creating a new table with `vim.tbl_map()`.
Here's some benchmark data:
https://gist.github.com/flrgh/349aecd8ca35d20cf0526ec8b218657c
In the large input benchmarks, the new function is ~2x faster. For small inputs (which are probably most common for `vim.notify()`), the speedup is even larger at 3-4x.
Other changes:
1. I noticed the same snippet appeared in multiple render modules, so I factored it out into …
> fix(render): handle large messages when calculating line width

- lua/notify/config/init.lua
- lua/notify/instance.lua
- lua/notify/render/compact.lua
- lua/notify/render/default.lua
- lua/notify/render/minimal.lua
- lua/notify/render/simple.lua
- lua/notify/render/wrapped-compact.lua
- lua/notify/service/notification.lua
- tests/manual/merge_duplicates.lua
Sometimes it happens that the same notification is displayed multiple times, usually due to some buggy callback. In such scenario, instead of displaying multiple duplicate notifications, they just replace the initial one. Renderers can use `#notif.duplicates` to display duplicates count. 
Specifying `merge_duplicates` as integer works as minimal duplicates count, but the way it is implemented right now may give somewhat unexpected result - it will replace only one of the previous notifications, but renderer will display total different duplicate counts on all, so overall duplicate count is not the sum of displayed ones. If this is unwanted then we may just remove option to use integer.
Example with the default renderer and `merge_duplicates = true`: …
> Merge duplicate notifications

- lua/notify/render/wrapped-compact.lua
Now uses nvim inline text to properly create padding. While I was at it, simplified the code a bit and also fixed two cases where some characters get cut off (notice in the first line of the first before image, the `fugiat` missing the `fug`).
before:
after:
code to test:
```lua
local msg = "Lorem ipsum dolor sit amet, officia excepteur ex fugiat reprehenderit enim labore culpa sint ad nisi Lorem pariatur mollit ex esse exercitation amet. Nisi anim cupidatat excepteur officia. Reprehenderit nostrud nostrud ipsum Lorem est aliquip amet voluptate voluptate dolor minim nulla est proident. Nostrud officia pariatur ut officia. Sit irure elit esse ea nulla sunt ex occaecat reprehenderit commodo officia dolor Lorem duis laboris cupidatat officia voluptate. Culpa proident adipisicing id nulla …
```
> feat: `wrapped-compact` uses nvim 0.10's inline text for proper padding

- lua/notify/config/init.lua
- lua/notify/stages/slide_out.lua
Hi! I needed an animation that shows the notification immediately so that `inputlist()` works. `inputlist()` expects synchroneous input, so nvim only has the chance to render the first frame of the notification animation. 
See https://github.com/folke/noice.nvim/issues/938
If the first frame is a transparent frame, I cannot see the prompt, so I decided to remove the first part of the `fade_in_slide_out` animation. I could have used `no_animation`, but this one looks nicer.
> Add slide_out animation

- README.md
- lua/notify/init.lua
- lua/notify/instance.lua
Adds the `:NotificationsClear` user command and the `require("notify").clear_history()` lua function to clear notification history.
The implementation simply resets the internal notification history table to an empty table. I am not sure how this interacts with any potential asynchronous activity, but I figured that if something is waiting to be pushed into the history table, it doesn't really matter for practical purposes if it gets pushed before or after the table is reset.
I added a documentation header in the code and I updated the readme to reflect the new command and new function.
Closes #158
> feat: Add ability to clear notification history

- lua/notify/stages/util.lua
Old implementation does not work properly because it -
1. overlaps the global statusline (off by 1 row), bottom limit
2. uses `tabline` option instead of `showtabline`, top limit
> fix(#189): correct the top-bottom slot limits

- lua/notify/service/buffer/highlights.lua
It seems like `metadata.priority` type is `string|integer` in nvim 0.11. This fixes the lua error.
> fix: priority type error for nvim 0.11

- lua/notify/service/notification.lua
The `vim.validate` function has deprecated one of its uses, which will be removed in neovim 1.0.
This updates the (sole?) use of vim.validate I could find. This was reported using nvim's |:checkhealth| command.
> fix: update vim.validate usage
